import React from "react";
import { authUser } from "@/utils/authentication/serverHelpers";
import ProfileSidebar from "../templates/profile/ProfileSidebar";
import { redirect } from "next/navigation";
import Footer from "../modules/Footer";
import Header from "../modules/Header";

export const metadata = {
  title: "Online Store Profile",
  description: "Profile in Online Store Generated by create next app",
};

export default async function ProfileLayout({ children }) {
  const user = await authUser();
  if (!user) {
    return redirect("/login-register");
  }
  return (
    <div className="flex flex-col min-h-screen">
      <Header isLogin={user ? true : false} />
      <main className="flex-grow">
        <div className="grid grid-cols-6 mt-5">
          <div className="col-span-1">
            <ProfileSidebar />
          </div>
          <div className="col-span-5">{children}</div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
